import React from "react";
import activemember1 from ".././../../assets/images/activememberimg1.png";
import activemember2 from ".././../../assets/images/activememberimg2.png";
const MemberData = [
  {
    img: activemember1,
    accounttype: "Premium",
    name: "Jane Cooper",
    memberid: "Member ID: ",
    memberidvalue: "34456",
    viewprofile: "View Profile",
    shortlist: "Mark Shortlist",
    age: "Age:",
    agevalue: "30 Years",
    height: "Height:",
    heightvalue: "5'10",
    religion: "Religion:",
    religionvalue: "Muslim",
    cast: "Caste:",
    castvalue: "Sunni",
    language: "First Language:",
    languagevalue: "English",
    maritalstatus: "Marital Status:",
    maritalstatusvalue: "Single",
  },
  {
    img: activemember2,
    accounttype: "Premium",
    name: "Jane Cooper",
    memberid: "Member ID:",
    memberidvalue: "34456",
    viewprofile: "View Profile",
    shortlist: "Mark Shortlist",
    age: "Age:",
    agevalue: "30 Years",
    height: "Height:",
    heightvalue: "5'10",
    religion: "Religion:",
    religionvalue: "Muslim",
    cast: "Caste:",
    castvalue: "Sunni",
    language: "First Language:",
    languagevalue: "English",
    maritalstatus: "Marital Status:",
    maritalstatusvalue: "Single",
  },
  {
    img: activemember1,
    accounttype: "Premium",
    name: "Jane Cooper",
    memberid: "Member ID:",
    memberidvalue: "34456",
    viewprofile: "View Profile",
    shortlist: "Mark Shortlist",
    age: "Age:",
    agevalue: "30 Years",
    height: "Height:",
    heightvalue: "5'10",
    religion: "Religion:",
    religionvalue: "Muslim",
    cast: "Caste:",
    castvalue: "Sunni",
    language: "First Language:",
    languagevalue: "English",
    maritalstatus: "Marital Status:",
    maritalstatusvalue: "Single",
  },
  {
    img: activemember2,
    accounttype: "Premium",
    name: "Jane Cooper",
    memberid: "Member ID:",
    memberidvalue: "34456",
    viewprofile: "View Profile",
    shortlist: "Mark Shortlist",
    age: "Age:",
    agevalue: "30 Years",
    height: "Height:",
    heightvalue: "5'10",
    religion: "Religion:",
    religionvalue: "Muslim",
    cast: "Caste:",
    castvalue: "Sunni",
    language: "First Language:",
    languagevalue: "English",
    maritalstatus: "Marital Status:",
    maritalstatusvalue: "Single",
  },
];

export default MemberData;
